site_name: Django Stripe

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview: index.md
  - Quickstart: library/quickstart.md
  - Actions:
      - Core:
          - Customers: library/actions/core/customers.md
          - Events: library/actions/core/events.md
      - Products:
          - Products: library/actions/products/products.md
          - Prices: library/actions/products/prices.md
          - Coupons: library/actions/products/coupons.md
      - Billings:
          - Subscriptions: library/actions/billings/subscriptions.md
      - Webhook: library/actions/webhooks.md
  - Management Commands: library/management_commands.md
  - Webhook: library/webhooks.md
  - Changelog: changelog.md

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/purnendukar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/purnendu-kar/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/purnendu_kar/
    - icon: fontawesome/solid/paper-plane
      link: mailto:purnendu.kar8@gmail.com

copyright: Copyright &copy; 2024 - 2030 Purnendu Kar

repo_url: https://github.com/purnendukar/django-stripe
repo_name: purnendukar/django-stripe
