site_name: Django Stripe

theme:
  name: material

nav:
  - Overview: index.md
  - Quickstart: library/quickstart.md
  - Models: library/models.md
  - Actions:
      - Core:
          - Customers: library/actions/core/customers.md
          - Events: library/actions/core/events.md
      - Products:
          - Products: library/actions/products/products.md
          - Prices: library/actions/products/prices.md
          - Coupons: library/actions/products/coupons.md
      - Card: library/actions/cards.md
      - Subscription: library/actions/subscriptions.md
      - Webhook: library/actions/webhooks.md
  - Management Commands: library/management_commands.md
  - Webhook: library/webhooks.md
  - Changelog: changelog.md

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
