name: Django-Stripe Doc Deployment

on:
  push:
    branches: [ "main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-material-extensions
          pip install mike

      - name: Set Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
        run: |
          mike deploy --update-aliases $(python -c "import importlib.metadata; print(importlib.metadata.version('django-stripe'))") latest --allow-empty --push  # Deploy to GitHub Pages
          mike set-default latest --allow-empty
